environment:
  matrix:
    - nodejs_version: "8"

init:
  # debugging Appveyor build. More info:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - curl -fsSL -o yarn.js https://github.com/yarnpkg/yarn/releases/download/v0.28.4/yarn-0.28.4.js
  - node ./yarn.js --version
  - node ./yarn.js install
  - node ./yarn.js run build

cache:
  - node_modules
  - .eslintcache

test_script:
  - node ./yarn.js run jest -- --color

# Don't actually build.
build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
